export enum BreadcrumbEnum {
  CAREERS = 'Carreras',
  CURRICULUMS = 'Mallas Curricualares',
  EVENTS = 'Eventos',
  INSTITUTIONS = 'Instituciones',
  SCHOOL_PERIODS = 'Periodos Lectivos',
  STUDENTS = 'Estudiantes',
  SUBJECTS = 'Asignaturas',
  ENROLLMENT_SUBJECTS = 'Asignaturas',
  TEACHERS = 'Docentes',
  FORM = 'Formulario',
  PROFILE = 'Mi Perfil',
  HOME = 'Home',
  ENROLLMENTS = 'Matrículas',
  USERS = 'Usuarios',
}
