export enum BreadcrumbEnum {
  CAREERS = 'Carreras',
  CURRICULUMS = 'Mallas Curriculares',
  EVENTS = 'Eventos',
  INSTITUTIONS = 'Instituciones',
  SCHOOL_PERIODS = 'Periodos Lectivos',
  STUDENTS = 'Estudiantes',
  SUBJECTS = 'Asignaturas',
  ENROLLMENT_SUBJECTS = 'Asignaturas',
  TEACHERS = 'Docentes',
  TEACHER_DISTRIBUTIONS = 'Distribución docente',
  FORM = 'Formulario',
  PROFILE = 'Mi Perfil',
  HOME = 'Home',
  ENROLLMENTS = 'Matrículas',
  ENROLLMENT_DETAILS = 'Detalle de Matrícula',
  ENROLLMENT_REQUEST = 'Proceso de Matrícula',
  USERS = 'Usuarios',
  TEACHER_CHARGE = 'Consolidado de notas',
  SUBJECT_REQUIREMENTS = 'Pre y Co Requisitos'
}
