import {PrimeIcons} from "primeng/api";

export enum IdButtonActionEnum {
  APPROVED = 'approved',
  REJECTED = 'rejected',
  ENROLLED = 'enrolled',
  REGISTERED = 'registered',
  SENT_REQUEST = 'sent_request',
  UPDATE = 'update',
  DELETE = 'delete',
  DOWNLOADS = 'downloads',
  SUSPEND = 'suspend',
  HIDE = 'hide',
  SELECT = 'select',
  REACTIVATE = 'reactivate',
  PARALLEL_CAPACITY = 'parallel_capacity',
  SHOW_EVENTS = 'show_events',
  OPEN_SCHOOL_PERIOD = 'open_school_period',
  CLOSE_SCHOOL_PERIOD = 'close_school_period',
  FILE_LIST = 'file_list',
  SUBJECT_REQUIREMENTS = 'subject_requirements',
}

export enum LabelButtonActionEnum {
  ACTIONS = 'Acciones',
  CREATE = 'Crear',
  CANCEL = 'Cancelar',
  RETURN = 'Regresar',
  SAVE = 'Guardar',
  UPDATE = 'Editar',
  DELETE = 'Eliminar',
  DOWNLOADS = 'Descargas',
  SUSPEND = 'Suspender',
  HIDE = 'Ocultar',
  SELECT = 'Seleccionar',
  REACTIVATE = 'Reactivar',
  SHOW_EVENTS = 'Mostar Eventos',
  OPEN_SCHOOL_PERIOD = 'Abrir Periodo Lectivo',
  CLOSE_SCHOOL_PERIOD = 'Cerrar Periodo Lectivo',
  FILE_LIST = 'Lista de Archivos',
  SUBJECT_REQUIREMENTS = 'Pre y Co Requisitos',
  SYNC = 'Sincronizar',
  CAREERS = 'Carreras',
  CURRICULUMS = 'Mallas Curriculares',
  SUBJECTS = 'Asignaturas',
  PARALLEL_CAPACITY = 'Capacidad Paralelos',
}

export enum IconButtonActionEnum {
  CREATE = 'pi pi-plus',
  SYNC = 'pi pi-sync',
  UPDATE = 'pi pi-pencil',
  CANCEL = 'pi pi-arrow-left',
  RETURN = 'pi pi-arrow-left',
  DOWNLOADS = 'pi pi-download',
  SAVE = 'pi pi-save',
  SUSPEND = 'pi pi-ban',
  PARALLEL_CAPACITY = 'pi pi-list',
  DELETE = 'pi pi-trash',
  HIDE = 'pi pi-eye-slash',
  SELECT = 'pi pi-check',
  REACTIVATE = 'pi pi-history',
  SHOW_EVENTS = 'Mostar Eventos',
  OPEN_SCHOOL_PERIOD = 'Abrir Periodo Lectivo',
  CLOSE_SCHOOL_PERIOD = 'Cerrar Periodo Lectivo',
  FILE_LIST = 'pi pi-file',
  SUBJECT_REQUIREMENTS = 'Pre y Co Requisitos',
}

export enum ClassButtonActionEnum {
  CREATE = 'p-button-success',
  CANCEL = 'p-button-warning',
  RETURN = 'p-button-warning',
  SAVE = '',
  SYNC = 'p-button-info',
  REDIRECT_SECONDARY = 'p-button-secondary',
  REDIRECT_HELP = 'p-button-help',
  UPDATE = 'Editar',
  DELETE = 'Eliminar',
  HIDE = 'Ocultar',
  SELECT = 'Seleccionar',
  REACTIVATE = 'Mostrar',
  SHOW_EVENTS = 'Mostar Eventos',
  OPEN_SCHOOL_PERIOD = 'Abrir Periodo Lectivo',
  CLOSE_SCHOOL_PERIOD = 'Cerrar Periodo Lectivo',
  FILE_LIST = 'Lista de Archivos',
  SUBJECT_REQUIREMENTS = 'Pre y Co Requisitos',
}

