export enum CatalogueCoreTypeEnum {
  ACADEMIC_PERIOD = 'ACADEMIC_PERIOD',
  ACADEMIC_STATE = 'ACADEMIC_STATE',
  BLOOD_TYPE = 'BLOOD_TYPE',
  CAREER_MODALITY = 'CAREER_MODALITY',
  EDUCATION_LEVEL = 'EDUCATION_LEVEL',
  ETHNIC_ORIGIN = 'ETHNIC_ORIGIN',
  DISABILITY_TYPE = 'DISABILITY_TYPE',
  IDENTIFICATION_TYPE = 'IDENTIFICATION_TYPE',
  INSTITUTION_PRACTICES_TYPE = 'INSTITUTION_PRACTICES_TYPE',
  GENDER = 'GENDER',
  MARITAL_STATUS = 'MARITAL_STATUS',
  PROJECT_SCOPE = 'PROJECT_SCOPE',
  SCHOLARSHIP_REASON_1 = 'SCHOLARSHIP_REASON_1',
  SCHOLARSHIP_REASON_2 = 'SCHOLARSHIP_REASON_2',
  SCHOLARSHIP_REASON_3 = 'SCHOLARSHIP_REASON_3',
  SCHOLARSHIP_REASON_4 = 'SCHOLARSHIP_REASON_4',
  SCHOLARSHIP_REASON_5 = 'SCHOLARSHIP_REASON_5',
  SCHOLARSHIP_REASON_6 = 'SCHOLARSHIP_REASON_6',
  SCHOLARSHIP_TYPE = 'SCHOLARSHIP_TYPE',
  SCHOLARSHIP_FUNDING_TYPE = 'SCHOLARSHIP_FUNDING_TYPE',
  STUDENT_OCCUPATION = 'STUDENT_OCCUPATION',
  STUDENT_INCOME_FOR = 'STUDENT_INCOME_FOR',
  REGISTRATION_TYPE = 'REGISTRATION_TYPE',
  SCHOOL_TYPE = 'SCHOOL_TYPE',
  SCHOOL_DAY = 'SCHOOL_DAY',
  SEX = 'SEX',
  STATE = 'STATE',
  TYPE = 'TYPE',
  WORKDAY = 'WORKDAY',
  YES_NO = 'YES_NO',
  YES_NO_NA = 'YES_NO_NA',
  SCHOOL_PERIODS_STATE = 'SCHOOL_PERIODS_STATE',
  EVENTS_STATE = 'EVENTS_STATE',
  INSTITUTIONS_STATE = 'INSTITUTIONS_STATE',
  CAREERS_STATE = 'CAREERS_STATE',
  CURRICULUMS_STATE = 'CURRICULUMS_STATE',
  SUBJECTS_STATE = 'SUBJECTS_STATE',
  SUBJECTS_TYPE = 'SUBJECTS_TYPE',
  PARALLEL = 'PARALLEL',
  ENROLLMENTS_WORKDAY = 'ENROLLMENTS_WORKDAY',
}
export enum CatalogueStateEnum {
  ENABLED = 'enabled',
  DISABLED = 'disabled',
}

export enum CatalogueCoreSchoolPeriodStateEnum {
  OPEN = 'open',
  CLOSE = 'close',
}

export enum CatalogueCoreSubjectRequirementTypeEnum {
  PREREQUISITE = 'prerequisite',
  CO_REQUISITE = 'co_requisite',
}

export enum CatalogueCareersModalityEnum {
  ON_SITE = 'on-site',
  SEMI_ON_SITE = 'semi-on-site',
  DISTANCE = 'distance',
  DUAL = 'dual',
  ONLINE = 'online',
  HYBRID = 'hybrid',
}

export enum UsersIdentificationTypeStateEnum {
  IDENTIFICATION = '1',
  PASSPORT = '2',
}
