export enum CatalogueCoreTypeEnum {
  ACADEMIC_PERIOD = 'ACADEMIC_PERIOD',
  BLOOD_TYPE = 'BLOOD_TYPE',
  CAREER_MODALITY = 'CAREER_MODALITY',
  CAREERS_STATE = 'CAREERS_STATE',
  CAREERS_TYPE = 'CAREERS_TYPE',
  CLASSROOMS_STATE = 'CLASSROOMS_STATE',
  CLASSROOMS_TYPE = 'CLASSROOMS_TYPE',
  CURRICULUMS_STATE = 'CURRICULUMS_STATE',
  DISABILITY_TYPE = 'DISABILITY_TYPE',
  EDUCATION_LEVEL = 'EDUCATION_LEVEL',
  ENROLLMENTS_ACADEMIC_STATE = 'ENROLLMENTS_ACADEMIC_STATE',
  ENROLLMENTS_STATE = 'ENROLLMENT_STATE',
  ENROLLMENTS_TYPE = 'ENROLLMENT_TYPE',
  ENROLLMENTS_WORKDAY = 'ENROLLMENTS_WORKDAY',
  ETHNIC_ORIGIN = 'ETHNIC_ORIGIN',
  EVENTS_STATE = 'EVENTS_STATE',
  GENDER = 'GENDER',
  HOME_OWNERSHIP = 'HOME_OWNERSHIP',
  HOME_FLOOR = 'HOME_FLOOR',
  HOME_ROOF = 'HOME_ROOF',
  HOME_TYPE = 'HOME_TYPE',
  HOME_WALL = 'HOME_WALL',
  IDENTIFICATION_TYPE = 'IDENTIFICATION_TYPE',
  INSTITUTION_PRACTICES_TYPE = 'INSTITUTION_PRACTICES_TYPE',
  INSTITUTIONS_STATE = 'INSTITUTIONS_STATE',
  MARITAL_STATUS = 'MARITAL_STATUS',
  FAMILY_INCOME = 'FAMILY_INCOME',
  PARALLEL = 'PARALLEL',
  PROJECT_SCOPE = 'PROJECT_SCOPE',
  REGISTRATION_TYPE = 'REGISTRATION_TYPE',
  SCHOLARSHIP_FUNDING_TYPE = 'SCHOLARSHIP_FUNDING_TYPE',
  SCHOLARSHIP_REASON = 'SCHOLARSHIP_REASON',
  SCHOLARSHIP_TYPE = 'SCHOLARSHIP_TYPE',
  SCHOOL_DAY = 'SCHOOL_DAY',
  SCHOOL_PERIODS_STATE = 'SCHOOL_PERIODS_STATE',
  SCHOOL_TYPE = 'SCHOOL_TYPE',
  SEX = 'SEX',
  STUDENT_INCOME_FOR = 'STUDENT_INCOME_FOR',
  STUDENT_LIVE = 'STUDENT_LIVE',
  STUDENT_OCCUPATION = 'STUDENT_OCCUPATION',
  SUBJECTS_STATE = 'SUBJECTS_STATE',
  SUBJECTS_TYPE = 'SUBJECTS_TYPE',
  YES_NO = 'YES_NO',
  YES_NO_NA = 'YES_NO_NA',
}

export enum CatalogueStateEnum {
  ENABLED = 'enabled',
  DISABLED = 'disabled',
}

export enum CatalogueCoreEnrollmentStateEnum {
  REQUEST_SENT = 'request_sent',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  ENROLLED = 'enrolled',
  REVOKED = 'revoked',
  PAID = 'paid',
  REGISTERED = 'registered',
}

export enum CatalogueCoreSchoolPeriodStateEnum {
  OPEN = 'open',
  CLOSE = 'close',
}

export enum CatalogueCoreSubjectRequirementTypeEnum {
  PREREQUISITE = 'prerequisite',
  CO_REQUISITE = 'co_requisite',
}

export enum CatalogueCareersModalityEnum {
  ON_SITE = 'on-site',
  SEMI_ON_SITE = 'semi-on-site',
  DISTANCE = 'distance',
  DUAL = 'dual',
  ONLINE = 'online',
  HYBRID = 'hybrid',
}

export enum UsersIdentificationTypeStateEnum {
  IDENTIFICATION = '1',
  PASSPORT = '2',
}
