export * from './address.model'
export * from './catalogue.model'
export * from './column.model'
export * from './file.model';
export * from './image.model';
export * from './location.model'
export * from './paginator.model';
export * from './phone.model';
export * from './state.model';
export * from './career.model';
export * from './curriculum.model';
export * from './information-student.model';
export * from './information-teacher.model';
export * from './institution.model';
export * from './student.model';
export * from './subject.model';
export * from './teacher.model';
export * from './school-period.model';
export * from './event.model';
export * from './model.model';
